// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD03da8ktnHirvzqagTZaMdeX3M9pKcWIo',
    appId: '1:721321520489:web:d8200d131e1b60854be1f8',
    messagingSenderId: '721321520489',
    projectId: 'finanzas-2debb',
    authDomain: 'finanzas-2debb.firebaseapp.com',
    storageBucket: 'finanzas-2debb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0RpVaADidxW_x87LxGKjW8ROZgz5EhH8',
    appId: '1:721321520489:android:c13e05a14be235a54be1f8',
    messagingSenderId: '721321520489',
    projectId: 'finanzas-2debb',
    storageBucket: 'finanzas-2debb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnaHiEXS6Vunl3ppooaRO-3FHT3eLpDmI',
    appId: '1:721321520489:ios:7d0e13d569fd83814be1f8',
    messagingSenderId: '721321520489',
    projectId: 'finanzas-2debb',
    storageBucket: 'finanzas-2debb.appspot.com',
    iosBundleId: 'com.example.learning1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnaHiEXS6Vunl3ppooaRO-3FHT3eLpDmI',
    appId: '1:721321520489:ios:7d0e13d569fd83814be1f8',
    messagingSenderId: '721321520489',
    projectId: 'finanzas-2debb',
    storageBucket: 'finanzas-2debb.appspot.com',
    iosBundleId: 'com.example.learning1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD03da8ktnHirvzqagTZaMdeX3M9pKcWIo',
    appId: '1:721321520489:web:cdcb166e2e69f6064be1f8',
    messagingSenderId: '721321520489',
    projectId: 'finanzas-2debb',
    authDomain: 'finanzas-2debb.firebaseapp.com',
    storageBucket: 'finanzas-2debb.appspot.com',
  );
}
